language: r
dist: xenial
latex: false
pandoc_version: 2.7.3

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'blogdown::install_hugo(force=TRUE)'
  - Rscript -e 'blogdown::build_site()'
  - touch public/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: ericmarcon/ericmarcon.github.io
  target_branch: master
